### ISSUE TITLE
Notify CTC members of new repository

### ISSUE THREAD

**Issue by trevnorris** [nodejs/node-eps#1]
@nodejs/ctc New repository to discuss in-depth changes to core. My initial thought was the `AsyncWrap` API, and how it should be made public. Additionally would be @indutny's `JSStream` API. Could also use this for @nodejs/http's suggestions on how to make the http module plug-able, or @nodejs/api on how to abstract the native API.

Going to leave this issue open for a week or two to give everyone time to notice this repo has been created.

**Comment by mikeal** [comment]
Would a name like "node-proposals" or "node-enhancements" be easier for newcomers?

**Comment by rvagg** [comment]
@mikeal tbh I'd prefer to route most proposals to nodejs/NG and reserve this for proper pull requests with fleshed-out proposals, in fact perhaps we should disable issues here? My fear about making is more accessible to newcomers is just going to result in massive amounts of issues for features that people want others to implement for them rather than constructive and concrete proposals backed by people who can do the work.

**Comment by mikeal** [comment]
If that's the case then +1 for disabling issues.

**Comment by jasnell** [comment]
+1

**Comment by orangemocha** [comment]
Great. One suggestions: make each proposal go into a separate branch, so that unrelated proposals remain isolated from each other.

**Comment by orangemocha** [comment]
Please ignore my comment about separate branches. I thought this repo was intended for code prototypes. Should have read the README first! :hushed:

**Comment by mhdawson** [comment]
+1 from me as well

**Comment by trevnorris** [comment]
Sounds good. Since this itself is an issue, I'll disable issues at the same time I close this.

**Comment by trevnorris** [comment]
This has been open long enough. I'll disable issues at the end of the week.
