### ISSUE TITLE
implements fibers in nodejs

### ISSUE THREAD

**Issue by yuu2lee4** [nodejs/node-eps#55]
like [fibjs](https://github.com/fibjs/fibjs) did,to get better performance。

**Comment by bnoordhuis** [comment]
That's not an enhancement proposal...  Closing.

**Comment by yuu2lee4** [comment]
why it isn't a proposal.

**Comment by ghost** [comment]
@yuu2lee4 if you'd like to see how things get into proposals I'm sure one of the node members would be glad to provide you with some guidance.

**Comment by bmeck** [comment]
@yuu2lee4 issues here are mostly for getting things ready to be EPS, a feature request most likely is better on the @nodejs/node repository.

If you want to make a proposal, please ensure you follow the right format: https://github.com/nodejs/node-eps#format and flesh out any API or semantic changes in the text of the proposal. My guess is this was closed because it made a request but did not specify the nature of how to implement the request and did not follow the format.

**Comment by bnoordhuis** [comment]
> why it isn't a proposal

Because you only cover the 'what', not the 'how'.  That makes it a feature request, not a feature proposal.

Those should go to nodejs/node and even then it should have at least some thought put into practicalities.  '_Node should solve the halting problem in polynomial time_' is technically a feature request but practically useless.

If you have concrete ideas on how to implement a feature and willing to commit to doing the actual work, this repo is the place and the README covers how to go about it.
