### ISSUE TITLE
"tree shaking" on nodejs

### ISSUE THREAD

**Issue by unional** [nodejs/node-eps#59]
Have it / can it / should it be considered?

The only benefit seems to be saving some memory consumption for the module resolution.
But if all references are resolved at runtime, then there is no benefit to be observed?

Or this may be fit into a larger discussion of "when to build"? 🌷

**Comment by jacktuck** [comment]
I think this is more userland tbh. 

Have you taken a look at prepack or closure compiler?

**Comment by dead-claudia** [comment]
This could only really be implemented at the VM level (V8), because it requires substantial static analysis. Also, it can't actually avoid loading or creating anything observable without implementor hooks (e.g. `.on("unhandledRejection", ...)`), because that would be in violation of the ES spec.

So IMHO this is something best asked on the es-discuss mailing list and the like, not here.

**Comment by bnoordhuis** [comment]
Answered, closing.
